default_platform(:ios)

platform :ios do
  desc "Deploy Dev flavor to Firebase App Distribution"
  lane :deploy_dev do
    setup_ci if ENV["CI"]
    match(type: "adhoc", readonly: is_ci)
    build_app(
      scheme: "dev",
      export_method: "ad-hoc"
    )
    firebase_app_distribution(
      app: ENV["FIREBASE_APP_ID_IOS_DEV"],
      groups: "testers",
      release_notes: "Dev iOS build from Fastlane CI"
    )
  end

  desc "Deploy Staging flavor to Apple TestFlight"
  lane :deploy_staging do

    setup_ci if ENV["CI"]
    match(type: "appstore", readonly: is_ci)
    build_app(
      scheme: "staging",
      export_method: "app-store"
    )
    upload_to_testflight(
      skip_waiting_for_build_processing: true
    )
  end

  desc "Deploy Prod flavor to App Store"
  lane :deploy_prod do
    setup_ci if ENV["CI"]
    match(type: "appstore", readonly: is_ci)
    build_app(
      scheme: "prod",
      export_method: "app-store"
    )
    upload_to_app_store(
      force: true,
      submit_for_review: false
    )
  end
end
