default_platform(:ios)

platform :ios do
  desc "Deploy Staging flavor to Apple TestFlight"
  lane :deploy_staging do
    setup_ci if ENV["CI"]
    match(type: "appstore", readonly: is_ci)
    build_app(
      scheme: "staging",
      export_method: "app-store"
    )
    upload_to_testflight(
      skip_waiting_for_build_processing: true
    )
  end

  desc "Deploy Prod flavor to App Store"
  lane :deploy_prod do
    setup_ci if ENV["CI"]
    match(type: "appstore", readonly: is_ci)
    build_app(
      scheme: "prod",
      export_method: "app-store"
    )
    upload_to_app_store(
      force: true,
      submit_for_review: false
    )
  end
end
